### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Innocent259** [faisalakb/Portfolio-website1#12]
Your design is looking good and its responsiveness is awesome but I'll recommend you add some animations in the background.

**Comment by faisalakb** [comment]
> Your design is looking good and its responsiveness is awesome but I'll recommend you add some animations in the background.

**Comment by Christelle-12** [comment]
Hi, great job👌, implementing this project!
However, it is a good practice always to have accessible web pages, have a look at them.😊

**Comment by omer-creator** [comment]
Great job, your project look perfect however you just need to make your navbar accessible.
